# Generated by Django 6.0.4 on 2026-05-02 14:01

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter a catagory name (Electonic, Cables, etc.', max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='category_name_case_insensitive', violation_error_message='Category already exists (case insensitive match)'),
        ),
    ]
