# Generated by Django 6.0.4 on 2026-05-04 19:04

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter a catagory name (Electonic, Cables, etc.)', max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a brand name (Apple, Samsung, etc.)', max_length=100, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='brand_name_case_insensitive', violation_error_message='Brand already exists (case insensitive match)')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.brand'),
        ),
    ]
